# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 7 Plus",
   "iPad Pro (12.9-inch)"
 ])

languages([
	"de-DE"
  # "en-US",
  # "de-DE"
])

# The name of the scheme which contains the UI Tests
scheme "App"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
workspace "../Code/" + File.read("./fastlane/Config/workspace.txt") + ".xcworkspace"

# For more information about all available options run
# snapshot --help
